select *
into #tempPointer
from dbo.PTRV2_JUL12

select * from #tempPointer

alter table #tempPointer
add UPCID int

alter table #tempPointer
Alter column UPCID varchar(128)

insert into #tempPointer (ID, ORGANISATION_NAME, SUB_BUILDING_NAME, BUILDING_NAME, BUILDING_NUMBER, PRIMARY_THORFARE, ALT_THORFARE_NAME1, SECONDARY_THORFARE, LOCALITY, TOWNLAND, TOWN, COUNTY, POSTCODE, BLPU, UNIQUE_BUILDING_ID, UPRN, USRN, LOCAL_COUNCIL, X_COR, Y_COR, TEMP_COORDS, BUILDING_STATUS, ADDRESS_STATUS, CLASSIFICATION, CREATION_DATE, COMMENCEMENT_DATE, ARCHIVED_DATE, ACTION, UDPRN, POSTTOWN, COA2001, LGD1992, WARD1992, SOA2001, PARL1992, WPC2008, LGD1984, WARD1984, ED1991_MAP, ED1991, SETTLEMENT, SETTLEMENTBAND, NRA_CODE, TTWA2007, POSTCODE_TRIM, ERB_temp, UPCID)
select ID, ORGANISATION_NAME, SUB_BUILDING_NAME, BUILDING_NAME, BUILDING_NUMBER, PRIMARY_THORFARE, ALT_THORFARE_NAME1, SECONDARY_THORFARE, LOCALITY, TOWNLAND, TOWN, COUNTY, POSTCODE, BLPU, UNIQUE_BUILDING_ID, UPRN, USRN, LOCAL_COUNCIL, X_COR, Y_COR, TEMP_COORDS, BUILDING_STATUS, ADDRESS_STATUS, CLASSIFICATION, CREATION_DATE, COMMENCEMENT_DATE, ARCHIVED_DATE, ACTION, UDPRN, POSTTOWN, COA2001, LGD1992, WARD1992, SOA2001, PARL1992, WPC2008, LGD1984, WARD1984, ED1991_MAP, ED1991, SETTLEMENT, SETTLEMENTBAND, NRA_CODE, TTWA2007, POSTCODE_TRIM, ERB_temp, (dbo.fn_extract_chars(BUILDING_NUMBER+PRIMARY_THORFARE, 'numbers')+postcode)
from dbo.PTRV2_JUL12  

select substring(postcode,3,PATINDEX('%[1234567890]%', Postcode) -1) from dbo.PTRV2_JUL12 where PATINDEX('%[1234567890]%', Postcode)>0

select substring(postcode,5,PATINDEX('%[1234567890]%', Postcode) -1) from dbo.PTRV2_JUL12 where PATINDEX('%[1234567890]%', Postcode)>0

select BUILDING_NUMBER+PRIMARY_THORFARE, postcode, (dbo.fn_extract_chars(BUILDING_NUMBER+PRIMARY_THORFARE, 'numbers')+postcode) from dbo.PTRV2_JUL12

select dbo.fn_extract_chars('22 Flat4', 'numbers')

select count(*)
from #tempPointer

select UPRN, count(*)
from #tempPointer
group by UPRN
having count(*)>1

select count(*)
from #tempPointer
where UPRN is null

select *
from #tempPointer
where len(UPRN)=9

select count(*)
from #tempPointer
where postcode is null

select count(*)
from #tempPointer
where UPCID is null