dbMemo "SQL" ="UPDATE POINTER SET upcid_n_wp = REPLACE(dbo.fn_extract_chars(ISNULL(SUB_BUILDING"
    "_NAME, '') + ISNULL(BUILDING_NAME, '') + ISNULL(BUILDING_NUMBER, '') + ISNULL(PR"
    "IMARY_THORFARE, ''), 'numbers') + ISNULL(POSTCODE, ''), ' ', ''),\015\012upcid_n"
    "_np = REPLACE(dbo.fn_extract_chars(ISNULL(SUB_BUILDING_NAME, '') + ISNULL(BUILDI"
    "NG_NAME, '') + ISNULL(BUILDING_NUMBER, '') + ISNULL(PRIMARY_THORFARE,'') + ISNUL"
    "L(POSTCODE, ''), 'numbers'), ' ', ''),\015\012upcid_ws_wp = dbo.unwanted(REPLACE"
    "(ISNULL(SUB_BUILDING_NAME, '') + ISNULL(BUILDING_NAME, '') + ISNULL(BUILDING_NUM"
    "BER, '') + ISNULL(PRIMARY_THORFARE, '') + ISNULL(POSTCODE, ''), ' ', '')),\015\012"
    "upcid_ws_np = dbo.unwanted(REPLACE(ISNULL(SUB_BUILDING_NAME,'') + ISNULL(BUILDIN"
    "G_NAME, '') + ISNULL(BUILDING_NUMBER, '') + ISNULL(PRIMARY_THORFARE, '') + dbo.f"
    "n_extract_chars(ISNULL(POSTCODE, ''), 'numbers'), ' ','')),\015\012upcid_cs_wp ="
    " dbo.unwanted(REPLACE(dbo.fn_extract_chars(ISNULL(SUB_BUILDING_NAME, '') + ISNUL"
    "L(BUILDING_NAME, '') + ISNULL(BUILDING_NUMBER, '') \015\012                     "
    " + ISNULL(PRIMARY_THORFARE, ''), 'letters') + ISNULL(POSTCODE, ''), ' ', '')),\015"
    "\012upcid_cs_np = dbo.unwanted(REPLACE(dbo.fn_extract_chars(ISNULL(SUB_BUILDING_"
    "NAME, '') \015\012                      + ISNULL(BUILDING_NAME, '') + ISNULL(BUI"
    "LDING_NUMBER, '') + ISNULL(PRIMARY_THORFARE, ''), 'letters') + dbo.fn_extract_ch"
    "ars(ISNULL(POSTCODE, ''), \015\012                      'numbers'), ' ', '')),\015"
    "\012upcid_n_nvd_wp = dbo.unwanted(REPLACE(dbo.fn_extract_chars(ISNULL(SUB_BUILDI"
    "NG_NAME, '') + ISNULL(BUILDING_NAME, '') + ISNULL(BUILDING_NUMBER, \015\012     "
    "                 '') + ISNULL(PRIMARY_THORFARE, ''), 'numbers') + dbo.nvd(ISNULL"
    "(SUB_BUILDING_NAME, '') + ISNULL(BUILDING_NAME, '') \015\012                    "
    "  + ISNULL(BUILDING_NUMBER, '') + ISNULL(PRIMARY_THORFARE, '')) + ISNULL(POSTCOD"
    "E, ''), ' ', '')),\015\012upcid_n_nvd_np = dbo.unwanted(REPLACE(dbo.fn_extract_c"
    "hars(ISNULL(SUB_BUILDING_NAME, '') + ISNULL(BUILDING_NAME, '') + ISNULL(BUILDING"
    "_NUMBER, '') + ISNULL(PRIMARY_THORFARE, ''), 'numbers') + dbo.nvd(ISNULL(SUB_BUI"
    "LDING_NAME, '') + ISNULL(BUILDING_NAME, '') + ISNULL(BUILDING_NUMBER, '') \015\012"
    "                      + ISNULL(PRIMARY_THORFARE, '')) + dbo.fn_extract_chars(ISN"
    "ULL(POSTCODE, ''), 'numbers'), ' ', '')),\015\012upcid_nvd_wp = dbo.unwanted(REP"
    "LACE(dbo.fn_extract_chars(dbo.nvd(ISNULL(SUB_BUILDING_NAME, '') + ISNULL(BUILDIN"
    "G_NAME, '') + ISNULL(BUILDING_NUMBER, '') + ISNULL(PRIMARY_THORFARE, '')), 'lett"
    "ers') + ISNULL(POSTCODE, ''), ' ', '')),\015\012upcid_nvd_np = dbo.unwanted(REPL"
    "ACE(dbo.fn_extract_chars(dbo.nvd(ISNULL(SUB_BUILDING_NAME, '') + ISNULL(BUILDING"
    "_NAME, '') + ISNULL(BUILDING_NUMBER, '') \015\012                      + ISNULL("
    "PRIMARY_THORFARE, '')), 'letters') + dbo.fn_extract_chars(ISNULL(POSTCODE, ''), "
    "'numbers'), ' ', '')),\015\012upcid_n_fc_wp = dbo.unwanted(REPLACE(dbo.fn_extrac"
    "t_chars(ISNULL(SUB_BUILDING_NAME, '') + ISNULL(BUILDING_NAME, '') + ISNULL(BUILD"
    "ING_NUMBER, '') + ISNULL(PRIMARY_THORFARE, ''), 'numbers') + LEFT(dbo.fn_extract"
    "_chars(ISNULL(SUB_BUILDING_NAME, '') + ISNULL(BUILDING_NAME, '') + ISNULL(BUILDI"
    "NG_NUMBER, '') \015\012                      + ISNULL(PRIMARY_THORFARE, ''), 'le"
    "tters'), 1) + ISNULL(POSTCODE, ''), ' ', '')),\015\012upcid_n_fc_np = dbo.unwant"
    "ed(REPLACE(dbo.fn_extract_chars(ISNULL(SUB_BUILDING_NAME, '') + ISNULL(BUILDING_"
    "NAME, '') + ISNULL(BUILDING_NUMBER, '') + ISNULL(PRIMARY_THORFARE, ''), 'numbers"
    "') + LEFT(dbo.fn_extract_chars(ISNULL(SUB_BUILDING_NAME, '') + ISNULL(BUILDING_N"
    "AME, '') + ISNULL(BUILDING_NUMBER, '') + ISNULL(PRIMARY_THORFARE, ''), 'letters'"
    "), 1) + dbo.fn_extract_chars(ISNULL(POSTCODE, ''), 'numbers'), ' ', '')),\015\012"
    "upcid_n_3c_wp = dbo.unwanted(REPLACE(dbo.fn_extract_chars(ISNULL(SUB_BUILDING_NA"
    "ME, '') + ISNULL(BUILDING_NAME, '') + ISNULL(BUILDING_NUMBER, '') + ISNULL(PRIMA"
    "RY_THORFARE, ''), 'numbers') + LEFT(dbo.fn_extract_chars(ISNULL(SUB_BUILDING_NAM"
    "E, '') + ISNULL(BUILDING_NAME, '') + ISNULL(BUILDING_NUMBER, '') + ISNULL(PRIMAR"
    "Y_THORFARE, ''), 'letters'), 3) + ISNULL(POSTCODE, ''), ' ', '')),\015\012upcid_"
    "n_3c_np = dbo.unwanted(REPLACE(dbo.fn_extract_chars(ISNULL(SUB_BUILDING_NAME, ''"
    ") + ISNULL(BUILDING_NAME, '') \015\012                      + ISNULL(BUILDING_NU"
    "MBER, '') + ISNULL(PRIMARY_THORFARE, ''), 'numbers') + LEFT(dbo.fn_extract_chars"
    "(ISNULL(SUB_BUILDING_NAME, '') \015\012                      + ISNULL(BUILDING_N"
    "AME, '') + ISNULL(BUILDING_NUMBER, '') + ISNULL(PRIMARY_THORFARE, ''), 'letters'"
    "), 3) + dbo.fn_extract_chars(ISNULL(POSTCODE, ''), \015\012                     "
    " 'numbers'), ' ', ''))"
dbMemo "Connect" ="ODBC;DSN=address;DATABASE=Address"
dbBoolean "ReturnsRecords" ="0"
dbInteger "ODBCTimeout" ="500"
dbBoolean "LogMessages" ="0"
dbByte "Orientation" ="0"
dbByte "PublishToWeb" ="1"
End
