dbMemo "SQL" ="Update D_address set upcid_n_wp = REPLACE(DBO.fn_extract_chars(ISNULL(Address1, "
    "'')+ISNULL(Address2, '')+ISNULL(Address3, '')+ISNULL(Address4, ''), 'numbers') +"
    " ISNULL(POSTCODE, ''), ' ', '')Update D_address set upcid_ws_wp = dbo.unwanted(R"
    "EPLACE(ISNULL(Address1, '')+ISNULL(Address2, '')+ISNULL(Address3, '')+ISNULL(Add"
    "ress4, '')+ISNULL(POSTCODE, ''), ' ', ''))Update D_address set upcid_n_nvd_wp = "
    "dbo.unwanted(REPLACE(DBO.fn_extract_chars(ISNULL(Address1, '')+ISNULL(Address2, "
    "'')+ISNULL(Address3, '')+ISNULL(Address4, ''), 'numbers')+DBO.nvd(ISNULL(Address"
    "1, '')+ISNULL(Address2, '')+ISNULL(Address3, '')+ISNULL(Address4, '')) +ISNULL(P"
    "OSTCODE, ''), ' ', ''))Update D_address set upcid_n_3c_wp = dbo.unwanted(REPLACE"
    "(DBO.fn_extract_chars(ISNULL(Address1, '')+ISNULL(Address2, '')+ISNULL(Address3,"
    " '')+ISNULL(Address4, ''), 'numbers')+LEFT(DBO.fn_extract_chars(ISNULL(Address1,"
    " '')+ISNULL(Address2, '')+ISNULL(Address3, '')+ISNULL(Address4, ''), 'letters'),"
    " 3)+ISNULL(POSTCODE, ''), ' ', ''))"
dbMemo "Connect" ="ODBC;DSN=address;DATABASE=Address"
dbBoolean "ReturnsRecords" ="0"
dbInteger "ODBCTimeout" ="0"
dbBoolean "LogMessages" ="0"
dbByte "Orientation" ="0"
dbByte "PublishToWeb" ="1"
End
