dbMemo "SQL" ="select a.UPCID_WS_WP as addUPCID_WS_WP, p.UPCID_WS_WP as PUPCID_WS_WP, p.UPRN in"
    "to tempPointer from G_Address a inner join POINTER p on a.UPCID_WS_WP = p.UPCID_"
    "WS_WP\015\012select addUPCID_WS_WP, COUNT(*) as counter into tempAddress from te"
    "mpPointer group by addUPCID_WS_WP having COUNT(*) >= 1\015\012Update main Set ma"
    "in.uprn = tp.uprn from G_Address main inner join tempPointer tp on main.UPCID_WS"
    "_WP = tp.PUPCID_WS_WP inner join tempAddress ta on main.UPCID_WS_WP = ta.addUPCI"
    "D_WS_WP where main.uprn Is Null and len(UPCID_WS_WP) > 1\015\012drop table tempP"
    "ointer\015\012drop table tempAddress\015\012select a.UPCID_N_NVD_WP as addUPCID_"
    "N_NVD_WP, p.UPCID_N_NVD_WP as PUPCID_N_NVD_WP, p.UPRN into tempPointer from G_Ad"
    "dress a inner join POINTER p on a.UPCID_N_NVD_WP = p.UPCID_N_NVD_WP\015\012selec"
    "t addUPCID_N_NVD_WP, COUNT(*) as counter into tempAddress from tempPointer group"
    " by addUPCID_N_NVD_WP having COUNT(*) >= 1\015\012Update main Set main.uprn = tp"
    ".uprn from G_Address main inner join tempPointer tp on main.UPCID_N_NVD_WP = tp."
    "PUPCID_N_NVD_WP inner join tempAddress ta on main.UPCID_N_NVD_WP = ta.addUPCID_N"
    "_NVD_WP where main.uprn Is Null and len(UPCID_N_NVD_WP) > 1\015\012drop table te"
    "mpPointer\015\012drop table tempAddress\015\012"
dbMemo "Connect" ="ODBC;DSN=address;DATABASE=Address"
dbBoolean "ReturnsRecords" ="0"
dbInteger "ODBCTimeout" ="0"
dbBoolean "LogMessages" ="0"
dbByte "Orientation" ="0"
dbByte "PublishToWeb" ="1"
End
