dbMemo "SQL" ="select a.UPCID_N_WP as addUPCID_N_WP, p.UPCID_N_WP as PUPCID_N_WP, p.UPRN into t"
    "empPointer from G_Address a inner join POINTER p on a.UPCID_N_WP = p.UPCID_N_WP\015"
    "\012select addUPCID_N_WP, COUNT(*) as counter into tempAddress from tempPointer "
    "group by addUPCID_N_WP having COUNT(*) >= 1\015\012Update main Set main.uprn = t"
    "p.uprn from G_Address main inner join tempPointer tp on main.UPCID_N_WP = tp.PUP"
    "CID_N_WP inner join tempAddress ta on main.UPCID_N_WP = ta.addUPCID_N_WP where m"
    "ain.uprn Is Null and len(UPCID_N_WP) > 1\015\012drop table tempPointer\015\012dr"
    "op table tempAddress\015\012select a.UPCID_N_NP as addUPCID_N_NP, p.UPCID_N_NP a"
    "s PUPCID_N_NP, p.UPRN into tempPointer from G_Address a inner join POINTER p on "
    "a.UPCID_N_NP = p.UPCID_N_NP\015\012select addUPCID_N_NP, COUNT(*) as counter int"
    "o tempAddress from tempPointer group by addUPCID_N_NP having COUNT(*) >= 1\015\012"
    "Update main Set main.uprn = tp.uprn from G_Address main inner join tempPointer t"
    "p on main.UPCID_N_NP = tp.PUPCID_N_NP inner join tempAddress ta on main.UPCID_N_"
    "NP = ta.addUPCID_N_NP where main.uprn Is Null and len(UPCID_N_NP) > 1\015\012dro"
    "p table tempPointer\015\012drop table tempAddress\015\012"
dbMemo "Connect" ="ODBC;DSN=address;DATABASE=Address"
dbBoolean "ReturnsRecords" ="0"
dbInteger "ODBCTimeout" ="0"
dbBoolean "LogMessages" ="0"
dbByte "Orientation" ="0"
dbByte "PublishToWeb" ="1"
End
