dbMemo "SQL" ="UPDATE POINTER SET upcid_n_wp = REPLACE(dbo.fn_extract_chars(ISNULL(SUB_BUILDING"
    "_NAME, '') + ISNULL(BUILDING_NAME, '') + ISNULL(BUILDING_NUMBER, '') + ISNULL(PR"
    "IMARY_THORFARE, ''), 'numbers') + ISNULL(POSTCODE, ''), ' ', ''),\015\012upcid_n"
    "_np = REPLACE(dbo.fn_extract_chars(ISNULL(SUB_BUILDING_NAME, '') + ISNULL(BUILDI"
    "NG_NAME, '') + ISNULL(BUILDING_NUMBER, '') + ISNULL(PRIMARY_THORFARE,'') + ISNUL"
    "L(POSTCODE, ''), 'numbers'), ' ', '')"
dbMemo "Connect" ="ODBC;DSN=address;DATABASE=Address"
dbBoolean "ReturnsRecords" ="0"
dbInteger "ODBCTimeout" ="500"
dbBoolean "LogMessages" ="0"
dbByte "Orientation" ="0"
dbByte "PublishToWeb" ="1"
End
