dbMemo "SQL" ="ALTER TABLE G_Address DROP COLUMN UPCID_CS_WP, UPCID_CS_NP, UPCID_N_NVD_WP, UPCI"
    "D_N_NVD_NP, UPCID_NVD_WP, UPCID_NVD_NP, UPCID_N_FC_WP, UPCID_N_FC_NP, UPCID_N_3C"
    "_WP, UPCID_N_3C_NP"
dbMemo "Connect" ="ODBC;DSN=address;DATABASE=Address"
dbBoolean "ReturnsRecords" ="0"
dbInteger "ODBCTimeout" ="0"
dbBoolean "LogMessages" ="0"
dbByte "Orientation" ="0"
dbByte "PublishToWeb" ="1"
End
