dbMemo "SQL" ="SELECT matchKeys.MatchKeys\015\012FROM matchKeys\015\012WHERE matchKeys IN (SELE"
    "CT COLUMN_NAME FROM getUPCIDColumns);\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbByte "PublishToWeb" ="1"
        dbText "Name" ="matchKeys.MatchKeys"
        dbLong "AggregateType" ="-1"
    End
End
