Version =20
VersionRequired =20
PublishOption =1
    Modal = NotDefault
    RecordSelectors = NotDefault
    NavigationButtons = NotDefault
    DividingLines = NotDefault
    AllowDesignChanges = NotDefault
    DefaultView =0
    ScrollBars =0
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridY =10
    Width =14513
    DatasheetFontHeight =11
    ItemSuffix =14
    Top =630
    Right =10215
    Bottom =8910
    DatasheetGridlinesColor =14806254
        0xb327bc960164e440
    End
    Caption ="Match Summary"
    DatasheetFontName ="Calibri"
    AllowDatasheetView =0
    AllowPivotTableView =0
    AllowPivotChartView =0
    AllowPivotChartView =0
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            SpecialEffect =3
            BackStyle =0
            BorderLineStyle =0
            Width =850
            Height =850
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            BackStyle =0
            OldBorderStyle =0
            BorderLineStyle =0
            SizeMode =3
            PictureAlignment =2
            Width =1701
            Height =1701
            BorderColor =16777215
            GridlineColor =16777215
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            Width =1701
            Height =283
            FontSize =11
            FontWeight =400
            FontName ="Calibri"
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            UseTheme =1
            Shape =1
            Gradient =12
            BackThemeColorIndex =4
            BackTint =60.0
            BorderLineStyle =0
            BorderColor =16777215
            BorderThemeColorIndex =4
            BorderTint =60.0
            ThemeFontIndex =1
            HoverThemeColorIndex =4
            HoverTint =40.0
            PressedThemeColorIndex =4
            PressedShade =75.0
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
        End
            Height =9751
            BackColor =15590879
            Name ="Detail"
            AlternateBackColor =15921906
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
                    PictureType =2
                    Left =7650
                    Width =4350
                    Height =2250
                    BorderColor =10921638
                    Name ="Image3"
                    Picture ="Logo_transparent"
                    GridlineColor =10921638

                    LayoutCachedLeft =7650
                    LayoutCachedWidth =12000
                    LayoutCachedHeight =2250
                    TabIndex =1
                End
                    SpecialEffect =0
                    BackStyle =1
                    OldBorderStyle =0
                    OverlapFlags =93
                    Left =7200
                    Top =3285
                    Width =5329
                    Height =5330
                    BackColor =9592887
                    BorderColor =10921638
                    Name ="Box0"
                    GridlineColor =10921638
                    LayoutCachedLeft =7200
                    LayoutCachedTop =3285
                    LayoutCachedWidth =12529
                    LayoutCachedHeight =8615
                    BackThemeColorIndex =4
                    BackShade =75.0
                End
                    OverlapFlags =215
                    TextAlign =3
                    Left =10995
                    Top =3738
                    Width =1125
                    Height =405
                    FontSize =16
                    FontWeight =700
                    BorderColor =8355711
                    ForeColor =16777215
                    Name ="totalRecords"
                    Caption =" "
                    GridlineColor =10921638
                    LayoutCachedLeft =10995
                    LayoutCachedTop =3738
                    LayoutCachedWidth =12120
                    LayoutCachedHeight =4143
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                End
                    OverlapFlags =215
                    TextAlign =3
                    Left =10998
                    Top =4986
                    Width =1125
                    Height =405
                    FontSize =16
                    FontWeight =700
                    BorderColor =8355711
                    ForeColor =16777215
                    Name ="nullUPRNs"
                    Caption =" "
                    GridlineColor =10921638
                    LayoutCachedLeft =10998
                    LayoutCachedTop =4986
                    LayoutCachedWidth =12123
                    LayoutCachedHeight =5391
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                End
                    OverlapFlags =215
                    TextAlign =3
                    Left =10998
                    Top =5609
                    Width =1125
                    Height =405
                    FontSize =16
                    FontWeight =700
                    BorderColor =8355711
                    ForeColor =16777215
                    Name ="matchedUPRNs"
                    Caption =" "
                    GridlineColor =10921638
                    LayoutCachedLeft =10998
                    LayoutCachedTop =5609
                    LayoutCachedWidth =12123
                    LayoutCachedHeight =6014
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                End
                    OverlapFlags =215
                    TextAlign =3
                    Left =10998
                    Top =6233
                    Width =1125
                    Height =405
                    FontSize =16
                    FontWeight =700
                    BorderColor =8355711
                    ForeColor =16777215
                    Name ="uprnsStillNull"
                    Caption =" "
                    GridlineColor =10921638
                    LayoutCachedLeft =10998
                    LayoutCachedTop =6233
                    LayoutCachedWidth =12123
                    LayoutCachedHeight =6638
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                End
                    OverlapFlags =215
                    Left =7540
                    Top =3738
                    Width =2835
                    Height =405
                    FontSize =16
                    BorderColor =8355711
                    ForeColor =16777215
                    Name ="Label7"
                    Caption ="Records Count :"
                    GridlineColor =10921638
                    LayoutCachedLeft =7540
                    LayoutCachedTop =3738
                    LayoutCachedWidth =10375
                    LayoutCachedHeight =4143
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                End
                    OverlapFlags =215
                    Left =7540
                    Top =4986
                    Width =2835
                    Height =405
                    FontSize =16
                    BorderColor =8355711
                    ForeColor =16777215
                    Name ="Label8"
                    Caption ="NULL before match : "
                    GridlineColor =10921638
                    LayoutCachedLeft =7540
                    LayoutCachedTop =4986
                    LayoutCachedWidth =10375
                    LayoutCachedHeight =5391
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                End
                    OverlapFlags =215
                    Left =7540
                    Top =5609
                    Width =2835
                    Height =405
                    FontSize =16
                    BorderColor =8355711
                    ForeColor =16777215
                    Name ="Label9"
                    Caption ="Matched UPRNs : "
                    GridlineColor =10921638
                    LayoutCachedLeft =7540
                    LayoutCachedTop =5609
                    LayoutCachedWidth =10375
                    LayoutCachedHeight =6014
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                End
                    OverlapFlags =215
                    Left =7540
                    Top =6233
                    Width =2835
                    Height =405
                    FontSize =16
                    BorderColor =8355711
                    ForeColor =16777215
                    Name ="Label10"
                    Caption ="Unmatched UPRNs : "
                    GridlineColor =10921638
                    LayoutCachedLeft =7540
                    LayoutCachedTop =6233
                    LayoutCachedWidth =10375
                    LayoutCachedHeight =6638
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                End
                    OverlapFlags =215
                    Left =7540
                    Top =7424
                    Width =2835
                    Height =405
                    FontSize =16
                    BorderColor =8355711
                    ForeColor =16777215
                    Name ="Label11"
                    Caption ="Match Percentage : "
                    GridlineColor =10921638
                    LayoutCachedLeft =7540
                    LayoutCachedTop =7424
                    LayoutCachedWidth =10375
                    LayoutCachedHeight =7829
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                End
                    PictureType =2
                    Left =11055
                    Top =6899
                    Width =1395
                    Height =1455
                    BorderColor =10921638
                    Name ="Image12"
                    Picture ="dotSelected"
                    GridlineColor =10921638

                    LayoutCachedLeft =11055
                    LayoutCachedTop =6899
                    LayoutCachedWidth =12450
                    LayoutCachedHeight =8354
                    TabIndex =2
                End
                    OverlapFlags =85
                    Left =9184
                    Top =8844
                    Width =1482
                    Height =510
                    FontSize =16
                    FontWeight =700
                    ForeColor =6373413
                    Name ="Command4"
                    Caption ="Close X"
                    OnClick ="[Event Procedure]"
                    GridlineColor =10921638

                    LayoutCachedLeft =9184
                    LayoutCachedTop =8844
                    LayoutCachedWidth =10666
                    LayoutCachedHeight =9354
                    ForeThemeColorIndex =4
                    ForeTint =100.0
                    ForeShade =50.0
                    Gradient =0
                    BackColor =14136213
                    BorderColor =14136213
                    HoverColor =16051931
                    HoverThemeColorIndex =8
                    HoverTint =20.0
                    PressedColor =9592887
                    HoverForeColor =6373413
                    HoverForeThemeColorIndex =4
                    HoverForeTint =100.0
                    HoverForeShade =50.0
                    PressedForeColor =4210752
                    WebImagePaddingLeft =2
                    WebImagePaddingTop =2
                    WebImagePaddingRight =1
                    WebImagePaddingBottom =1
                End
                    OverlapFlags =85
                    Left =7200
                    Top =2610
                    Width =5265
                    Height =510
                    FontSize =18
                    FontWeight =700
                    BorderColor =8355711
                    ForeColor =9592887
                    Name ="title"
                    Caption =" "
                    GridlineColor =10921638
                    LayoutCachedLeft =7200
                    LayoutCachedTop =2610
                    LayoutCachedWidth =12465
                    LayoutCachedHeight =3120
                    ForeThemeColorIndex =4
                    ForeTint =100.0
                    ForeShade =75.0
                End
                    OverlapFlags =247
                    TextAlign =3
                    Left =11160
                    Top =7425
                    Width =1125
                    Height =405
                    FontSize =16
                    FontWeight =700
                    BorderColor =8355711
                    ForeColor =9592887
                    Name ="percentageMatched"
                    Caption =" "
                    GridlineColor =10921638
                    LayoutCachedLeft =11160
                    LayoutCachedTop =7425
                    LayoutCachedWidth =12285
                    LayoutCachedHeight =7830
                    ForeThemeColorIndex =4
                    ForeTint =100.0
                    ForeShade =75.0
                End
            End
        End
    End
End
CodeBehindForm
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub Command4_Click()
DoCmd.Close
statusmsg = SysCmd(acSysCmdSetStatus, "Select the option to carry out next.")
End Sub
